import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
// import "./globals.css";
import "./assets/lib/bootstrap/dist/css/bootstrap.min.css"
import "tailwindcss";
import "./assets/css/styles.css";
import "./assets/css/site.css";

import Link from "next/link";
import { Suspense } from "react";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi" suppressHydrationWarning>
      <body  suppressHydrationWarning>
        <Suspense fallback={null}>
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
            {children}
            {/* <Toaster /> */}
          </ThemeProvider>
        </Suspense>
      </body>
    </html>
  );
}
